<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:meta="https://api.nav.gov.hu/definitions/form_xsd_metaschema/1.0"
        xmlns:tns="https://soap.api.nav.gov.hu/definitions/model/2.0/26A215/1.0"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        targetNamespace="https://soap.api.nav.gov.hu/definitions/model/2.0/26A215/1.0">
   <import namespace="https://api.nav.gov.hu/definitions/form_xsd_metaschema/1.0"
           schemaLocation="form_xsd_metaschema.xsd"/>
   <element name="Doc_26A215"
            type="tns:Doc_26A215_Type"
            meta:metaType="DocMetaType">
      <annotation>
         <documentation>Negyedéves/Éves bevallás a szociálpolitikai menetdíj-támogatás személyszállítási tevékenységek szerinti adatairól</documentation>
      </annotation>
   </element>
   <simpleType name="Enum_26A215_0A0001D004A">
      <annotation>
         <documentation>Enum értékek </documentation>
      </annotation>
      <restriction base="xs:string">
         <enumeration value="H"/>
      </restriction>
   </simpleType>
   <simpleType name="Enum_26A215_0A0001D005A">
      <annotation>
         <documentation>Enum értékek </documentation>
      </annotation>
      <restriction base="xs:string">
         <enumeration value="N"/>
         <enumeration value="E"/>
      </restriction>
   </simpleType>
   <simpleType name="Enum_26A215_0A0001D006A">
      <annotation>
         <documentation>Enum értékek </documentation>
      </annotation>
      <restriction base="xs:string">
         <enumeration value="F"/>
         <enumeration value="V"/>
         <enumeration value="A"/>
         <enumeration value="E"/>
         <enumeration value="M"/>
         <enumeration value="B"/>
         <enumeration value="D"/>
      </restriction>
   </simpleType>
   <simpleType name="Enum_26A215_0A0001D007A">
      <annotation>
         <documentation>Enum értékek </documentation>
      </annotation>
      <restriction base="xs:string">
         <enumeration value="1"/>
         <enumeration value="2"/>
         <enumeration value="3"/>
      </restriction>
   </simpleType>
   <complexType name="Doc_26A215_Type">
      <annotation>
         <documentation>A teljes bizonylat szerkezetet leíró típus</documentation>
      </annotation>
      <sequence>
         <element name="Form_26A215"
                  type="tns:Form_26A215_Type"
                  minOccurs="1"
                  maxOccurs="1"
                  meta:metaType="FormMetaType">
            <annotation>
               <documentation>26A215 részbizonylat</documentation>
            </annotation>
         </element>
      </sequence>
   </complexType>
   <complexType name="Form_26A215_Type">
      <annotation>
         <documentation>A teljes nyomtatvány 26A215 részbiztonylatának szerkezetét leíró típus.</documentation>
      </annotation>
      <sequence>
         <element name="Block_120025"
                  type="tns:Block_26A215_120025_Type"
                  minOccurs="0"
                  meta:metaType="BlockMetaType">
            <annotation>
               <documentation>Azonosító adatok</documentation>
            </annotation>
         </element>
         <element name="Block_120001"
                  type="tns:Block_26A215_120001_Type"
                  minOccurs="0"
                  meta:metaType="BlockMetaType">
            <annotation>
               <documentation>Szociálpolitikai menetdíj-támogatás személyszállítási tevékenységek szerinti bontásban</documentation>
            </annotation>
         </element>
      </sequence>
   </complexType>
   <complexType name="Block_26A215_120025_Type">
      <annotation>
         <documentation>Azonosító adatok</documentation>
      </annotation>
      <all>
         <element name="FieldGroup_120002"
                  type="tns:FieldGroup_26A215_120002_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Adózó adatai</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120011"
                  type="tns:FieldGroup_26A215_120011_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Ügyintéző adatai</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120012"
                  type="tns:FieldGroup_26A215_120012_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Bevallás jellemzői</documentation>
            </annotation>
         </element>
      </all>
   </complexType>
   <complexType name="Block_26A215_120001_Type">
      <annotation>
         <documentation>Szociálpolitikai menetdíj-támogatás személyszállítási tevékenységek szerinti bontásban</documentation>
      </annotation>
      <all>
         <element name="FieldGroup_120028"
                  type="tns:FieldGroup_26A215_120028_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Országos, regionális és elővárosi személysz. közszolg. tev, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként országos, regionális és elővárosi közlekedési szolgáltató által végzett személysz. közszolg. tev.</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120026"
                  type="tns:FieldGroup_26A215_120026_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Helyi személyszállítási közszolgáltatási tevékenység, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként helyi szolgáltató által végzett személyszállítási közszolgáltatási tevékenység</documentation>
            </annotation>
         </element>
         <element name="FieldGroup_120027"
                  type="tns:FieldGroup_26A215_120027_Type"
                  minOccurs="0"
                  meta:metaType="FieldGroupMetaType">
            <annotation>
               <documentation>Komp- és révközlekedésben nyújtott személyszállítási közszolgáltatási tevékenység, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként végzett komp- és révközlekedési tevékenység</documentation>
            </annotation>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120002_Type">
      <annotation>
         <documentation>Adózó adatai</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001C001A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Adószáma (adószám)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C002A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Adóazonosító jele (adóazonositó)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="10"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C004A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Jogelőd adószáma (jogelőd_adószám)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C005A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Adózó neve (adózó_neve)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="80"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120011_Type">
      <annotation>
         <documentation>Ügyintéző adatai</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001C006A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Neve (ügyintéző_neve)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="80"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0A0001C007A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Telefonszáma (ügyintéző_telefonszáma)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="40"/>
                  <pattern value="\P{C}+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120012_Type">
      <annotation>
         <documentation>Bevallás jellemzői</documentation>
      </annotation>
      <all>
         <element name="Field_0A0001D001A"
                  minOccurs="0"
                  type="xs:date"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallási időszak ¦ Kezdete (bev_időszak_kezdete)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D002A"
                  minOccurs="0"
                  type="xs:date"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallási időszak ¦ Vége (bev_időszak_vége)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D004A"
                  minOccurs="0"
                  type="tns:Enum_26A215_0A0001D004A"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallás ¦ Jellege (bev_jelleg)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D005A"
                  minOccurs="0"
                  type="tns:Enum_26A215_0A0001D005A"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallás ¦ Gyakorisága (bev_gyakoriság)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D006A"
                  minOccurs="0"
                  type="tns:Enum_26A215_0A0001D006A"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallás ¦ Típusa (bev_típus)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001D007A"
                  minOccurs="0"
                  type="tns:Enum_26A215_0A0001D007A"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Bevallás ¦ Fajtája (bev_fajta)</documentation>
            </annotation>
         </element>
         <element name="Field_0A0001C003A"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Egyéb adatok ¦ Hibásnak minősített bevallás vonalkódja (vonalkód)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="10"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120028_Type">
      <annotation>
         <documentation>Országos, regionális és elővárosi személysz. közszolg. tev, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként országos, regionális és elővárosi közlekedési szolgáltató által végzett személysz. közszolg. tev.</documentation>
      </annotation>
      <all>
         <element name="Field_0B0001C0001AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 1. 50%-os jegy ([01]A1)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0002AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 2. 50%-os összekapcsolt vagy integrált jegy ([01]A2)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0003AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 3. 90%-os bérlet ([01]A3)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0004AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 4. 90%-os összekapcsolt vagy integrált bérlet ([01]A4)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0005AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 5. Autóbuszközlekedés esetén ([01]A5)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001C0006AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 6. Vasúti közlekedés (ideértve a vasút-villamos közlekedést is) esetén ([01]A6)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120026_Type">
      <annotation>
         <documentation>Helyi személyszállítási közszolgáltatási tevékenység, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként helyi szolgáltató által végzett személyszállítási közszolgáltatási tevékenység</documentation>
      </annotation>
      <all>
         <element name="Field_0B0001D0010AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 10. Budapest ([01]A10)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0011AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 11. Megyei jogú városok - kizárólag autóbuszra ([01]A11)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0012AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 12. Megyei jogú városok - kizárólag villamosra (beleértve a vasút-villamost is) ([01]A12)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0013AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 13. Megyei jogú városok - villamosra (beleértve a vasút-villamost is), vagy trolibuszra ([01]A13)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0014AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 14. Megyei jogú városok - villamosra és trolibuszra ([01]A14)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0015AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 15. Megyei jogú városok - villamosra (beleértve a vasút-villamost is) és autóbuszra ([01]A15)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0016AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 16. Megyei jogú városok - autóbuszra, villamosra és trolibuszra (kombinált) ([01]A16)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0017AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 17. Egyéb település ([01]A17)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0018AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 18. Budapest ([01]A18)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0019AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 19. Villamos (beleértve a vasút-villamost is), trolibusz- és autóbusz-közlekedéssel rendelkező megyei jogú város ([01]A19)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0020AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 20. Villamos- és autóbusz-közlekedéssel rendelkező megyei jogú város ([01]A20)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0021AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 21. Kizárólag autóbuszközlekedéssel rendelkező megyei jogú város ([01]A21)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001D0022AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 22. Egyéb település ([01]A22)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
   <complexType name="FieldGroup_26A215_120027_Type">
      <annotation>
         <documentation>Komp- és révközlekedésben nyújtott személyszállítási közszolgáltatási tevékenység, összekapcsolt vagy integrált személyszállítási közszolgáltatás részeként végzett komp- és révközlekedési tevékenység</documentation>
      </annotation>
      <all>
         <element name="Field_0B0001E0025AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 25. Jegy ([01]A25)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001E0026AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Kedvezményes személyszállítási közszolgáltatási tevékenységek ¦ 26. Bérlet ([01]A26)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
         <element name="Field_0B0001E0027AA"
                  minOccurs="0"
                  meta:metaType="FieldMetaType">
            <annotation>
               <documentation>Díjmentes személyszállítási közszolgáltatási tevékenységek ¦ 27. Menetdíj ([01]A27)</documentation>
            </annotation>
            <simpleType>
               <restriction base="string">
                  <minLength value="1"/>
                  <maxLength value="11"/>
                  <pattern value="[0-9]+"/>
               </restriction>
            </simpleType>
         </element>
      </all>
   </complexType>
</schema>
